version: '3.8'

services:
  ai-code-reviewer:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BITBUCKET_ACCESS_TOKEN=${BITBUCKET_ACCESS_TOKEN}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - PORT=5000
      - FLASK_DEBUG=false
      - API_RATE_LIMIT=60
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s